basePath: /
host: localhost:8080
info:
  contact:
    email: huliquns@126.com
    name: Liqun Hu
  description: This is a sample server celler server.
  title: Rest API
  version: "1.0"
paths:
  /api/auth/signin:
    post:
      consumes:
      - application/json
      parameters:
      - in: query
        maxLength: 100
        name: IdentifyCode
        required: true
        type: string
      - enum:
        - WEB
        - MOBILE
        in: query
        name: LoginType
        required: true
        type: string
      - in: query
        maxLength: 100
        name: MagicNo
        required: true
        type: string
      - in: query
        maxLength: 100
        name: Username
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Signin
      tags:
      - Auth
  /api/v1/Test/GetTestById:
    post:
      consumes:
      - application/json
      parameters:
      - in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: GetTestById
      tags:
      - Test
securityDefinitions:
  "":
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
